baseURL = "http://www.gusonex.cloud"
languageCode = "en-us"
summaryLength = "10"
theme = "kross"
title = "Gusonex | AWS Cloud, Big Data & ML, Virtual Reality"
[[menu.main]]
URL = "services/serverless/"
name = "Serverless"
parent = "Services"
weight = 5
[[menu.main]]
URL = "services/cloud/"
name = "Cloud"
parent = "Services"
weight = 4
[[menu.main]]
URL = "services/big-data/"
name = "Big Data"
parent = "Services"
weight = 3
[[menu.main]]
URL = "services/virtual-augmented-reality"
name = "Virtual / Augmented Reality"
parent = "Services"
weight = 2
[[menu.main]]
URL = "services/serverless/"
name = "Why is this website so fast?"
parent = "Services"
weight = 1
[[menu.main]]
URL = "privacy-policy"
name = "Privacy Policy"
parent = "About"
weight = 2
[[menu.main]]
URL = "impressum"
name = "Impressum"
parent = "About"
weight = 1
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5
[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 3
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 1
[[menu.main]]
URL = "about"
name = "About"
parent = "about"
weight = 2
[params]
author = "Justin Güse"
description = "Solution Architect for Cloud, Big Data, Virtual and Augmented Reality, and distributed computing."
googleAnalitycsID = "UA-56269619-16"
home = "Home"
logo = "images/logo.png"
[params.contact]
enable = true
formAction = "https://formspree.io/mjvbqzrj"
[params.footer]
address = "Austraße 3a, 5020 Salzburg, Austria"
email = "info@gusonex.cloud"
phone = "+1 ‪(413) 296-5682"
phone2 = "+43 677 62577902"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
